# Generated by Django 3.0.8 on 2020-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drlicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='titulo',
            field=models.CharField(default='aaaa', max_length=255),
            preserve_default=False,
        ),
    ]
